name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
version-template: "$MAJOR.$MINOR.0.b$PATCH"
change-template: '- #$NUMBER - $TITLE (@$AUTHOR)'
latest: false
prerelease: true
categories:

  - title: "⚠ Breaking Changes"
    labels:
      - 'breaking-change'

  - title: "🐛 Bugfixes"
    labels:
      - 'bugfix'

  - title: "🚀 Features"
    labels:
      - 'feature'
      - 'enhancement'
      - 'new-feature'
      - 'new-provider'

  - title: '🧰 Maintenance'
    labels:
      - 'ci'
      - 'documentation'
      - 'maintenance'

  - title: '⬆️ Dependencies'
    collapse-after: 1
    labels:
      - 'dependencies'

template: |

  ## :bow: Thanks to our contributors

  Special thanks to the following contributors who helped with this release:

  $CONTRIBUTORS

  ## Full Changelog

  $CHANGES

version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'new-feature'
      - 'new-provider'
  default: patch
